// Auto-generated by WorkbookSchemaGenerator on 2025-09-09T16:26:35.159Z
// Tables: Requisition, RequisitionItem, RequisitionApproval, Project, ProjectMember, Person, Unit
import { TableDefinition } from "./UniversalRepo";

export interface Requisition {
  id: number;
  name: string;
  createdAt: Date;
  createdBy: number;
  dueDate: number;
  projectId: number;
  projectName: string;
}

export const requisitionDef: TableDefinition<Requisition> = {
  columns: {
    id: { type: "number", required: true, final: true },
    name: { type: "string", required: true },
    createdAt: { type: "date", required: true, calculated: true, final: true },
    createdBy: { type: "number", required: true, final: true, referenceTo: "Person" },
    dueDate: { type: "number", required: true, final: true },
    projectId: { type: "number", required: true, final: true, referenceTo: "Project" },
    projectName: { type: "string", required: true, calculated: true, final: true }
  },
  names: {
    id: "Id",
    name: "Name",
    createdAt: "CreatedAt",
    createdBy: "CreatedBy",
    dueDate: "DueDate",
    projectId: "ProjectId",
    projectName: "ProjectName"
  },
  order: ["id", "name", "createdAt", "createdBy", "dueDate", "projectId", "projectName"]
};

export interface RequisitionItem {
  id: number;
  productName: string;
  requisitionId: number;
  quantity: number;
  unitId: number;
  unit: string;
  categoryId: number;
  category: string;
  commentInternal: string;
  comment: string;
}

export const requisitionItemDef: TableDefinition<RequisitionItem> = {
  columns: {
    id: { type: "number", required: true, final: true },
    productName: { type: "string", required: true, final: true },
    requisitionId: { type: "number", required: true, final: true, referenceTo: "Requisition" },
    quantity: { type: "number", required: true, final: true },
    unitId: { type: "number", required: true, final: true, referenceTo: "Unit" },
    unit: { type: "string", required: true, final: true },
    categoryId: { type: "number", required: true, final: true, referenceTo: "Category" },
    category: { type: "string", required: true, final: true },
    commentInternal: { type: "string", required: true, final: true },
    comment: { type: "string", required: true, final: true }
  },
  names: {
    id: "Id",
    productName: "ProductName",
    requisitionId: "RequisitionId",
    quantity: "Quantity",
    unitId: "UnitId",
    unit: "Unit",
    categoryId: "CategoryId",
    category: "Category",
    commentInternal: "CommentInternal",
    comment: "Comment"
  },
  order: ["id", "productName", "requisitionId", "quantity", "unitId", "unit", "categoryId", "category", "commentInternal", "comment"]
};

export interface RequisitionApproval {
  id: number;
  requisitionId: number;
  personId: number;
  personName: string;
  createdAt: Date;
  createdBy: number;
  decisionDate: number;
  decision: number;
}

export const requisitionApprovalDef: TableDefinition<RequisitionApproval> = {
  columns: {
    id: { type: "number", required: true, final: true },
    requisitionId: { type: "number", required: true, final: true, referenceTo: "Requisition" },
    personId: { type: "number", required: true, final: true, referenceTo: "Person" },
    personName: { type: "string", required: true, calculated: true, final: true },
    createdAt: { type: "date", required: true, calculated: true, final: true },
    createdBy: { type: "number", required: true, final: true, referenceTo: "Person" },
    decisionDate: { type: "number", required: true, final: true },
    decision: { type: "number", required: true, final: true, default: 0 }
  },
  names: {
    id: "Id",
    requisitionId: "RequisitionId",
    personId: "PersonId",
    personName: "PersonName",
    createdAt: "CreatedAt",
    createdBy: "CreatedBy",
    decisionDate: "DecisionDate",
    decision: "Decision"
  },
  order: ["id", "requisitionId", "personId", "personName", "createdAt", "createdBy", "decisionDate", "decision"]
};

export interface Project {
  id: number;
  name: string;
  createdAt: Date;
  createdBy: number;
}

export const projectDef: TableDefinition<Project> = {
  columns: {
    id: { type: "number", required: true, final: true },
    name: { type: "string" },
    createdAt: { type: "date", calculated: true },
    createdBy: { type: "number", referenceTo: "Person" }
  },
  names: {
    id: "Id",
    name: "Name",
    createdAt: "CreatedAt",
    createdBy: "CreatedBy"
  },
  order: ["id", "name", "createdAt", "createdBy"]
};

export interface ProjectMember {
  id: number;
  projectId: number;
  personId: number;
  createdAt: Date;
  createdBy: number;
  roleId: number;
}

export const projectMemberDef: TableDefinition<ProjectMember> = {
  columns: {
    id: { type: "number", required: true, final: true },
    projectId: { type: "number", referenceTo: "Project" },
    personId: { type: "number", referenceTo: "Person" },
    createdAt: { type: "date", calculated: true },
    createdBy: { type: "number" },
    roleId: { type: "number", referenceTo: "Role" }
  },
  names: {
    id: "Id",
    projectId: "ProjectId",
    personId: "PersonId",
    createdAt: "CreatedAt",
    createdBy: "CreatedBy",
    roleId: "RoleId"
  },
  order: ["id", "projectId", "personId", "createdAt", "createdBy", "roleId"]
};

export interface Person {
  id: number;
  firstName: string;
  lastName: string;
  fullName: string;
  email: string;
  createdAt: Date;
  createdBy: number;
  isActive: boolean;
}

export const personDef: TableDefinition<Person> = {
  columns: {
    id: { type: "number", required: true, final: true },
    firstName: { type: "string" },
    lastName: { type: "string" },
    fullName: { type: "string", calculated: true },
    email: { type: "string", required: true },
    createdAt: { type: "date" },
    createdBy: { type: "number" },
    isActive: { type: "boolean", default: true }
  },
  names: {
    id: "Id",
    firstName: "FirstName",
    lastName: "LastName",
    fullName: "FullName",
    email: "Email",
    createdAt: "CreatedAt",
    createdBy: "CreatedBy",
    isActive: "IsActive"
  },
  order: ["id", "firstName", "lastName", "fullName", "email", "createdAt", "createdBy", "isActive"]
};

export interface Unit {
  id: number;
  name: string;
  shortName: string;
}

export const unitDef: TableDefinition<Unit> = {
  columns: {
    id: { type: "number", required: true, final: true },
    name: { type: "string", required: true, final: true },
    shortName: { type: "string", required: true, final: true }
  },
  names: {
    id: "Id",
    name: "Name",
    shortName: "ShortName"
  },
  order: ["id", "name", "shortName"]
};