// Auto-generated by WorkbookSchemaGenerator on 2025-09-06T13:13:21.081Z
// Tables: Person, Project
import { TableDefinition } from "./UniversalRepo";

export interface Person {
  id: number;
  firstName: string;
  lastName: string;
  fullName: string;
  email: string;
  isActive: boolean;
  createdAt: Date;
}

export const personDef: TableDefinition<Person> = {
  columns: {
    id: { type: "number", required: true, final: true },
    firstName: { type: "string" },
    lastName: { type: "string" },
    fullName: { type: "string", calculated: true },
    email: { type: "string" },
    isActive: { type: "boolean" },
    createdAt: { type: "date", required: true, final: true }
  },
  names: {
    id: "Id",
    firstName: "FirstName",
    lastName: "LastName",
    fullName: "FullName",
    email: "Email",
    isActive: "IsActive",
    createdAt: "CreatedAt"
  },
  order: ["id", "firstName", "lastName", "fullName", "email", "isActive", "createdAt"]
};

export interface Project {
  id: number;
  name: string;
  isActive: boolean;
  createdAt: Date;
  createdBy: string;
}

export const projectDef: TableDefinition<Project> = {
  columns: {
    id: { type: "number" },
    name: { type: "string" },
    isActive: { type: "boolean" },
    createdAt: { type: "date" },
    createdBy: { type: "string" }
  },
  names: {
    id: "Id",
    name: "Name",
    isActive: "IsActive",
    createdAt: "CreatedAt",
    createdBy: "CreatedBy"
  },
  order: ["id", "name", "isActive", "createdAt", "createdBy"]
};